### ISSUE TITLE
Avoid showing NAs when turnning display_numbers TRUE

### ISSUE THREAD

**Issue by ellyyuyang** [jbengler/tidyheatmaps#4]
Hi, 

Thanks for developing and sharing this tool!

As described in the title, any way I can avoid showing "NA" when I have "display_numbers" on TRUE? 

Thanks!
Yu

**Comment by jbengler** [comment]
Hi Yu,

when you have missing values in the data, they will be printed as `NA`.
I do not see an easy way to selectively hide the `NA`s while keeping the numbers.

You could take manual control over the values to be printed. But this is quite cumbersome.

See example:
```
library(tidyheatmaps)

df <- data.frame(gene = rep(paste0("sample", 1:3), times = 3),
                 sample = rep(paste0("gene", 1:3), each = 3),
                 expression = c(2.3, NA, 4.3, 2.1, 1.9, 4.9, 5.2, 1.2, 3.4))

tidyheatmap(df = df,
            rows = gene,
            columns = sample,
            values = expression,
            scale = "row",
            display_numbers = TRUE
)

tidyheatmap(df = df,
            rows = gene,
            columns = sample,
            values = expression,
            scale = "row",
            display_numbers = matrix(c("Whatever", "you", "would", "like", "to", "put", "in", "the", "cells"),
                                     nrow = 3, ncol = 3, byrow = TRUE)
)
```

Best,
Broder

**Comment by ellyyuyang** [comment]
Thanks Broder! Your answer inspired me in pre-defining my matrix and replacing NAs by empty cells in the matrix, then feed this matrix to display_numbers. And this worked well! Thanks!

Best,
Yu
