### ISSUE TITLE
cluster extraction

### ISSUE THREAD

**Issue by nishimuy** [jbengler/tidyheatmaps#7]
Can I extract the cluster information based on what tidyheatmaps does? 
I am using the line below and nicely made clusters of genes, and I want to extract the clusters of genes afterwards.

cluster_cols = TRUE
cluster_rows = TRUE

Thank you in advance fro your help.

**Comment by jbengler** [comment]
Hi @nishimuy 

I can think of two ways:

1. you can try to work with what's inside `tree_row` and `tree_col` in your tidyplots object:
```
my_heatmap <- tidyheatmap(<put your code here>)
my_heatmap$tree_row
```

2. You can do the clustering outside tidyheatmaps and provide the `hclust` object to `cluster_cols` and `cluster_rows`:
```
my_clustering <- hclust(<put your code here>)

tidyheatmap(<put your code here>,
   cluster_cols = my_clustering)
```

Let me know what worked best for you.
